### ISSUE TITLE
New InfoButtons Vagrant VM

### ISSUE THREAD

**Issue by DSSUSER** [logicahealth/InfoButtons#10]
I am using the new InfoButtons Vagrant VM.
I have it installed on my PC, where I now have the entire process completely documented.
I also installed it on two demo laptops, which will be taken to customer sites.
However, many things have changed with the new Vagrant VM.
Using the full-blown, full install version, the path we used to point our application to was:
     infobuttons-service/infoRequest?
This PATH no longer exists in the Infobuttons Vagrant VM version.
I am ready to test the application, but don't know where to look.
There are multiple PATHS to "infobuttons-service", but there is no file, anywhere on the new VM, called "infoRequest".
Can anyone tell me what the new entry should be, to take the place of the above noted entry?
Thanks in advance, and have a great holiday season.

**Comment by wahmedswl** [comment]
Hi,
   Is there any pre-configured VM available? @DSSUSER where did you get  InfoButtons Vagrant VM.

Thanks

**Comment by gdelfiol** [comment]
We are planning to release a Vagrant VM, but right now it is still a work in progress.

**Comment by wahmedswl** [comment]
@gdelfiol thanks for you reply. Is there any expected timeline?

Thanks

**Comment by gdelfiol** [comment]
Hopefully by the end of April. We could give you access prior to that if you would like to help us test it.

**Comment by wahmedswl** [comment]
@gdelfiol, that would be great. I would love to test and give you feedback.

Thanks

**Comment by gdelfiol** [comment]
Ok, I will let you know when we’re ready for that.

**Comment by wahmedswl** [comment]
@gdelfiol thanks, really appreciate that.

**Comment by wahmedswl** [comment]
@gdelfiol is VM available now? It would be great if something available that can be easily deployed. Thanks

**Comment by gdelfiol** [comment]
Hopefully, an alpha version will be available by the end of this week.

**Comment by wahmedswl** [comment]
@gdelfiol that would be great 👍

**Comment by gdelfiol** [comment]
The OpenInfobutton VM pre-release is now available at https://github.com/VHAINNOVATIONS/InfoButtons/releases/tag/oib-2.1.  Please start with the installation instructions (https://github.com/VHAINNOVATIONS/InfoButtons/releases/download/oib-2.1/OpenInfobutton.VM.install.docx)

We welcome any suggestions on how to improve the instructions and the VM.

**Comment by wahmedswl** [comment]
Hi, @gdelfiol getting following error 

```
RawFile#0 failed to create the raw output file /Users/andrew/DevApps/OpenInfobuttonDev/NewInfobuttonVM/ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND).


Result Code: 
E_FAIL (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}
```

**Comment by wahmedswl** [comment]
Hi, @gdelfiol i have updated the config file and VM boot up, whats the user/pwd for the VM?

Thanks

**Comment by aniskand** [comment]
Hi, you should be able to just type "vagrant ssh" and it will log you in.

**Comment by jrivasg** [comment]
Hi @wahmedswl I have the same problem, how do you update the config file?

Thanks

**Comment by wahmedswl** [comment]
@jrivasg i have updated the path in ```OpenInfobutton_default_1494833254530_81355.vbox``` and ```OpenInfobutton_default_1494833254530_81355.vbox-prev``` at VirtualBox VMs folder, mine was at ```C:\Users\waqas\VirtualBox VMs\OpenInfobutton_default_1494833254530_81355```

**Comment by wahmedswl** [comment]
@aniskand i have tried vagrant ssh but i am getting
```
{ OpenInfobutton }  » vagrant ssh
ssh_exchange_identification: read: Connection reset by peer
```

Its a Windows Machine with VirtualBox installed

Any help would be appreciated, thanks

**Comment by aniskand** [comment]
Try connecting then with username "ubuntu" and password "vagrant".

**Comment by wahmedswl** [comment]
@aniskand, sorry but vagrant password doesn't work

**Comment by jrivasg** [comment]
@wahmedswl Thanks for the info, but now send a new error with the new path.

RawFile#0 failed to create the raw output file C:\Users\FabLab\VirtualBox VMs\InfoButtonVM_default_1494924076348_3601 (VERR_ACCESS_DENIED).

Did the same happen to you?

**Comment by wahmedswl** [comment]
@jrivasg nope, seems like some sort of permission issue. Do you have any other VM in VirtualBox which was/is working?

I have Windows7 Machine, It seems like there was some kinda bug in VirtualBox for Windows10, please check https://www.virtualbox.org/ticket/14425

**Comment by jrivasg** [comment]
@wahmedswl Ok thaks, it's working, but now I have de same problem to connect, user: ubuntu, but vagrant is not the password.
@gdelfiol Please user and password? Thanks

**Comment by aniskand** [comment]
Hi everyone,

Another user found a solution to his problems starting up the VM by setting the "Port Mode:" setting in VirtualBox to "Disconnected". See this screenshot,

![image](https://cloud.githubusercontent.com/assets/5632298/26108908/1777d658-3a0b-11e7-9837-e3edd9fb2fbd.png)

As for the username/password issue, I'm not sure how to fix it. I had the same problem locally but managed to fix it by adding config.ssh.username = "ubuntu" to the Vagrantfile. I added that to the Vagrantfile on the release as well so I assumed that fix would work for everyone.

**Comment by gdelfiol** [comment]
Several people reported issues similar to the above and were able to fix the problem by changing the Virtual Box port settings.
