### ISSUE TITLE
Artifact ID's changed in POM's, Clean builds do not work

### ISSUE THREAD

**Issue by kbalthaser** [logicahealth/InfoButtons#2]
Just tried checking out and building for the first time, and it is clear that in the last check in the artifact ID's were changed throughout the source tree, but the dependency entries were not updated to reflect this, this if you do not already have the artifacts under the old names in your local repo, you will get many dependency errors

**Comment by wahmedswl** [comment]
HI, is this be related to #12? I have also tried but cannot build.

Thanks
