### ISSUE TITLE
Can't finish download of VM

### ISSUE THREAD

**Issue by vsetteacher** [logicahealth/InfoButtons#22]
Tried to download VM several time and it always failed when it was almost done. Am I missing anything here? Any advice?

**Comment by lrasmus** [comment]
I just tried and was able to download it.  Curious what OS + browser you've tested with, and if you've just tried from one network location or multiple (e.g., does it always fail at work, but not at home)?

**Comment by vsetteacher** [comment]
Thank you for reply. I managed to download it this morning. Looks like some
odd network issue.
